config-version: 2

name: "data_eng_project"
version: "3.0.0"
require-dbt-version: ">=1.5.0"

dbt-cloud:
  project-id: 70403103994596 # Put your project id here

profile: analytics # Put your profile here

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  "dbt_date:time_zone": "America/Los_Angeles"

semantic-models:
  +time_spine: ref('metricflow_time_spine')

seeds:
  data_eng_project:
    +schema: raw
    jaffle-data:
      +enabled: true

models:
  data_eng_project:
    staging:
      +materialized: view
    marts:
      +materialized: table
      +group: data_eng
